# Generated by Django 4.2.7 on 2025-09-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('angul', 'Angul'), ('balangir', 'Balangir'), ('balasore', 'Balasore'), ('bargarh', 'Bargarh'), ('bhadrak', 'Bhadrak'), ('boudh', 'Boudh'), ('cuttack', 'Cuttack'), ('deogarh', 'Deogarh'), ('dhenkanal', 'Dhenkanal'), ('gajapati', 'Gajapati'), ('ganjam', 'Ganjam'), ('jagatsinghpur', 'Jagatsinghpur'), ('jajpur', 'Jajpur'), ('jharsuguda', 'Jharsuguda'), ('kalahandi', 'Kalahandi'), ('kandhamal', 'Kandhamal'), ('kendrapara', 'Kendrapara'), ('keonjhar', 'Keonjhar'), ('khordha', 'Khordha'), ('koraput', 'Koraput'), ('malkangiri', 'Malkangiri'), ('mayurbhanj', 'Mayurbhanj'), ('nabarangpur', 'Nabarangpur'), ('nayagarh', 'Nayagarh'), ('nuapada', 'Nuapada'), ('puri', 'Puri'), ('rayagada', 'Rayagada'), ('sambalpur', 'Sambalpur'), ('sonepur', 'Sonepur'), ('sundargarh', 'Sundargarh')], max_length=50)),
                ('crop', models.CharField(choices=[('rice', 'Rice'), ('maize', 'Maize'), ('wheat', 'Wheat'), ('groundnut', 'Groundnut'), ('mung', 'Mung'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('turmeric', 'Turmeric')], max_length=50)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=20)),
                ('sowing_date', models.DateField()),
                ('field_area', models.FloatField(help_text='Area in hectares')),
                ('irrigation', models.CharField(choices=[('none', 'None/Rainfed'), ('tubewell', 'Tube well'), ('canal', 'Canal'), ('lift', 'Lift'), ('drip', 'Drip')], max_length=20)),
                ('soil_type', models.CharField(choices=[('alluvial', 'Alluvial'), ('lateritic', 'Lateritic'), ('red_black', 'Red & Black'), ('saline', 'Saline')], max_length=20)),
                ('soil_health_card', models.BooleanField(default=False)),
                ('seed_variety', models.CharField(choices=[('local', 'Local'), ('hyv', 'HYV'), ('hybrid', 'Hybrid')], max_length=20)),
                ('pest_presence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_yield', models.FloatField()),
                ('confidence_interval', models.CharField(max_length=50)),
                ('estimated_gain', models.FloatField()),
                ('action_1', models.TextField()),
                ('action_2', models.TextField()),
                ('action_3', models.TextField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advisory.farminput')),
            ],
        ),
    ]
